Create form
huzaifakhan0308/personal-portfolio pull request #3
Opened 2022-12-06 20:45 UTC by huzaifakhan0308

create the form-section which is required in microverse day 2 pair project

2022-12-06 21:51 UTC, Gambit142 requested changes
Hi @huzaifakhan0308 👋, 

Good job so far!
## Highlights
- All linters checks passed ✔️ 
- The form submits to the designated site ✔️ 
- HTML validations are present ✔️ 

However, there are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️

### I am requesting this change here because I can't add inline comments to your `README.md` file:

- Your README.md file is missing some significant sections. Kindly include these sections in your project:
  - Key Features
  - Future Features
- For the Install section, the command is incorrect. You can't install this project with `npm i`. Kindly make these changes on your README.md before submitting it for another review. 👍 
- Kindly remove the logo section from the file also.

![image](https://user-images.githubusercontent.com/77106962/206030678-d6757130-6b6a-4412-be83-33cd4a9f2c6f.png)

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:

N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2022-12-06 21:51 UTC, Gambit142 commented on index.css
> +}
- [ ] Great work designing this section. It would be nice to make your design look identical to that of the Figma template that you chose. If you look at the Figma template that you chose, there is a `border-top-left-radius` that was implemented but in yours, there is none, I would advise you to give the `border-top-left-radius` a value of `100px` to make it look alike. 👍 💻 

### Your Design

![image](https://user-images.githubusercontent.com/77106962/206026389-5b81a5e8-c5e5-4ec5-bf07-b28ff43ffa28.png)

### Figma Template

![image](https://user-images.githubusercontent.com/77106962/206026489-caf27858-7dbf-45ae-8c13-2dcb16faafe4.png)

2022-12-06 21:51 UTC, Gambit142 commented on index.css
> +}
- [ ] Kindly use the recommended CSS property from the Figma template on this element:

- `font-size`
- `font-weight`
- `text-align`
- `color`

Please get the correct values for these CSS properties from the Figma template. 👍 

### Your Design

![image](https://user-images.githubusercontent.com/77106962/206026627-041c986f-0de9-465b-bed2-d2b0526d9739.png)

### Figma Template

![image](https://user-images.githubusercontent.com/77106962/206026689-16773481-cd2f-4d17-aece-d98fdcfe33d9.png)

2022-12-06 21:51 UTC, Gambit142 commented on index.css
> +}
- [ ] If you look at the Figma template, the form inputs have a `border-radius` of `8px`. Kindly implement it so that your form inputs are identical to the ones shown on the Figma template. 👍 

### Your Template

![image](https://user-images.githubusercontent.com/77106962/206027568-46464751-1478-48c1-add6-5c1d1ba17831.png)

### Figma Template

![image](https://user-images.githubusercontent.com/77106962/206027669-f1838325-eba3-4a43-b243-93d2b7b9fe18.png)

2022-12-06 21:51 UTC, Gambit142 commented on index.css
> +}
- [ ] For the form button, kindly implement the button interactions `hover`, `enable`, `disable` and `active`. You can see details of the hover and active pseudo states in this section on the template view.

![image](https://user-images.githubusercontent.com/77106962/206028769-22fa02ae-ee22-486c-902d-6d91c3d1869b.png)

2022-12-06 21:51 UTC, Gambit142 commented on index.html
> +            required></textarea>
- [ ] Great work using the correct HTML validation for this form input. However, I noticed the correct placeholder attribute value was not used. Yours states `Enter text here` while that on the Figma template says `Write your message here`. Kindly implement it 💻 👍

2022-12-07 10:50 UTC, huzaifakhan0308 commented
Sir will you please ask me....that where is the logo section you ask me to
remove it from the file but I can't see the logo section

On Wed, 7 Dec 2022, 2:51 am Francis Ugorji, ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> Hi @huzaifakhan0308 <https://github.com/huzaifakhan0308> 👋,
>
> Good job so far!
> Highlights
>
>    - All linters checks passed ✔️
>    - The form submits to the designated site ✔️
>    - HTML validations are present ✔️
>
> However, there are some issues that you still need to work on to go to the
> next project but you are almost there!
> Required Changes ♻️ I am requesting this change here because I can't add
> inline comments to your README.md file:
>
>    - Your README.md file is missing some significant sections. Kindly
>    include these sections in your project:
>       - Key Features
>       - Future Features
>    - For the Install section, the command is incorrect. You can't install
>    this project with npm i. Kindly make these changes on your README.md
>    before submitting it for another review. 👍
>    - Kindly remove the logo section from the file also.
>
> [image: image]
> <https://user-images.githubusercontent.com/77106962/206030678-d6757130-6b6a-4412-be83-33cd4a9f2c6f.png>
>
> *Check the comments under the review.*
> Optional suggestions
>
> *Every comment with the [OPTIONAL] prefix is not crucial enough to stop
> the approval of this PR. However, I strongly recommend you to take them
> into account as they can make your code better.*
>
> You can also consider:
>
> N/A
>
> Cheers and Happy coding!👏👏👏
>
> Feel free to leave any questions or comments in the PR thread if something
> is not 100% clear.
> Please, remember to tag me in your question so I can receive the
> notification.
>
> *Please, do not open a new Pull Request for re-reviews. You should use the
> same Pull Request submitted for the first review, either valid or invalid
> unless it is requested otherwise.*
> ------------------------------
>
> *As described in the Code reviews limits policy
> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you have a
> limited number of reviews per project (check the exact number in your
> Dashboard). If you think that the code review was not fair, you can request
> a second opinion using this form <https://airtable.com/shrQAqnBwek5a0O0s>.*
>
> ------------------------------
>
> In index.css
> <https://github.com/huzaifakhan0308/personal-portfolio/pull/3#discussion_r1041467440>
> :
>
> > +.form-section {
>
> +  display: flex;
>
> +  flex-direction: column;
>
> +  align-items: center;
>
> +  background-color: #6955ff;
>
> +  width: 100%;
>
> +}
>
>
>
>    - Great work designing this section. It would be nice to make your
>    design look identical to that of the Figma template that you chose. If you
>    look at the Figma template that you chose, there is a
>    border-top-left-radius that was implemented but in yours, there is
>    none, I would advise you to give the border-top-left-radius a value of
>    100px to make it look alike. 👍 💻
>
> Your Design
>
> [image: image]
> <https://user-images.githubusercontent.com/77106962/206026389-5b81a5e8-c5e5-4ec5-bf07-b28ff43ffa28.png>
> Figma Template
>
> [image: image]
> <https://user-images.githubusercontent.com/77106962/206026489-caf27858-7dbf-45ae-8c13-2dcb16faafe4.png>
> ------------------------------
>
> In index.css
> <https://github.com/huzaifakhan0308/personal-portfolio/pull/3#discussion_r1041477121>
> :
>
> > +.info-formsection {
>
> +  padding: 20px 20px;
>
> +  color: white;
>
> +  font-family: "Poppins", sans-serif;
>
> +}
>
>
>
>    -
>
>    Kindly use the recommended CSS property from the Figma template on
>    this element:
>    -
>
>    font-size
>    -
>
>    font-weight
>    -
>
>    text-align
>    -
>
>    color
>
> Please get the correct values for these CSS properties from the Figma
> template. 👍
> Your Design
>
> [image: image]
> <https://user-images.githubusercontent.com/77106962/206026627-041c986f-0de9-465b-bed2-d2b0526d9739.png>
> Figma Template
>
> [image: image]
> <https://user-images.githubusercontent.com/77106962/206026689-16773481-cd2f-4d17-aece-d98fdcfe33d9.png>
> ------------------------------
>
> In index.css
> <https://github.com/huzaifakhan0308/personal-portfolio/pull/3#discussion_r1041481560>
> :
>
> > +.name-input-formsection {
>
> +  height: 5vh;
>
> +  width: 100%;
>
> +  padding-left: 10px;
>
> +  outline: none;
>
> +}
>
> +
>
> +.email-input-formsection {
>
> +  height: 5vh;
>
> +  width: 100%;
>
> +  margin-top: 15px;
>
> +  padding-left: 10px;
>
> +  outline: none;
>
> +}
>
> +
>
> +.form-text-area {
>
> +  width: 100%;
>
> +  padding: 10px;
>
> +  margin-top: 15px;
>
> +  outline: none;
>
> +}
>
>
>
>    - If you look at the Figma template, the form inputs have a
>    border-radius of 8px. Kindly implement it so that your form inputs are
>    identical to the ones shown on the Figma template. 👍
>
> Your Template
>
> [image: image]
> <https://user-images.githubusercontent.com/77106962/206027568-46464751-1478-48c1-add6-5c1d1ba17831.png>
> Figma Template
>
> [image: image]
> <https://user-images.githubusercontent.com/77106962/206027669-f1838325-eba3-4a43-b243-93d2b7b9fe18.png>
> ------------------------------
>
> In index.css
> <https://github.com/huzaifakhan0308/personal-portfolio/pull/3#discussion_r1041485675>
> :
>
> > +.form-button {
>
> +  margin-top: 15px;
>
> +  width: 14vh;
>
> +  border-radius: 8px;
>
> +  height: 5vh;
>
> +  border: none;
>
> +  color: #6070ff;
>
> +  font-family: "Poppins", sans-serif;
>
> +  font-weight: 600;
>
> +  font-size: 15px;
>
> +}
>
>
>
>    - For the form button, kindly implement the button interactions hover,
>    enable, disable and active. You can see details of the hover and
>    active pseudo states in this section on the template view.
>
> [image: image]
> <https://user-images.githubusercontent.com/77106962/206028769-22fa02ae-ee22-486c-902d-6d91c3d1869b.png>
> ------------------------------
>
> In index.html
> <https://github.com/huzaifakhan0308/personal-portfolio/pull/3#discussion_r1041491036>
> :
>
> > +        <textarea name="Message" cols="30" rows="6" placeholder="Enter text here" maxlength="500" class="form-text-area"
>
> +            required></textarea>
>
>
>
>    - Great work using the correct HTML validation for this form input.
>    However, I noticed the correct placeholder attribute value was not used.
>    Yours states Enter text here while that on the Figma template says Write
>    your message here. Kindly implement it 💻 👍
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/huzaifakhan0308/personal-portfolio/pull/3#pullrequestreview-1207336841>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A3I36YF44LNJIWVBM6FAX3DWL6YN7ANCNFSM6AAAAAASV7E6K4>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-12-07 12:40 UTC, Owusu-Desmond requested changes
Hi @huzaifakhan0308  :wave: 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some changes you still need to work on before you move on to the next project but you are almost there.

<img src="https://media1.giphy.com/media/KyBesf8kNT6s88SEgb/giphy.gif"/>

 ## Highlights :+1: 
:heavy_check_mark: Good commit history.
:heavy_check_mark: No linter errors.
:heavy_check_mark: Good PR


 ## Required Changes ♻️
_Check the comments under the review._

- [ ] Your project should have been invalidated by the first reviewer. But please note :warning:, Next time make sure that your pull request is made from the “feature branch” into the `main` (which should be the default branch )but not from the “feature branch” into the `feature branch`(That is what you did). :smile: 

- [ ] As requested by the previous code reviewer, In your project readme file, the Microverse logo is not showing
    
    ##### In your readme file you have this
    ![Screenshot from 2022-12-07 12-24-18](https://user-images.githubusercontent.com/92303891/206179140-729c1327-8c33-4418-b3f4-2dbb4682001b.png)
    
    ##### In microverse readme template
    ![Screenshot from 2022-12-07 12-27-43](https://user-images.githubusercontent.com/92303891/206179427-80dc2433-5fe3-4117-9b47-cc057a5adf68.png)
    
    To solve this, visit [microverse readme template](https://github.com/microverseinc/readme-template), right-click on the logo, and save it in your project directory but make sure that while saving the logo in your project directory, it should be named [murple_logo.png](https://github.com/microverseinc/readme-template/blob/master/murple_logo.png)

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-07 12:40 UTC, Owusu-Desmond commented on index.css
> +}
- [ ] Good to give your `Get in touch` a hover effect but while making changes requested by the previous reviewer, you have your `Get in touch` button differ from the Figma design.

| Your Design (button text in two lines, height, and width) |Figma Design (button text in one line) |
| :---:   | :---: | 
| ![Screenshot from 2022-12-07 12-01-31](https://user-images.githubusercontent.com/92303891/206175461-fe3c6846-6df7-4f09-909d-a398e0917ed5.png) | ![Screenshot from 2022-12-07 12-09-10](https://user-images.githubusercontent.com/92303891/206175843-6c1c0fd2-4cda-4387-ab10-0db1e1fa23e2.png) |

2022-12-07 12:40 UTC, Owusu-Desmond commented on index.css
> +
- [ OPTIONAL ] Why are you repeating many CSS properties for your input field? Why don't your give one class name to your input fields and that class name to style all your field without repeating the same CSS properties? Have you forgotten to follow the [DRY(DON'T REPEAT YOURSELF) principle](https://vanseodesign.com/css/dry-principles/)? :smile:

2022-12-07 18:09 UTC, closed without merging