Creating form
huzaifakhan0308/personal-portfolio pull request #4
Opened 2022-12-07 18:13 UTC by huzaifakhan0308

Made CSS style changes and also add some changes in README file

2022-12-07 18:22 UTC, tugsem requested changes
## Invalid Code Review Request ❌ 

Hi @huzaifakhan0308 , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

You have submitted a project, that doesn't have the correct github flow. I suggest you to change the base branch using this Github doc -> [Changing the base branch of a pull request](https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-base-branch-of-a-pull-request)
- Also, please don't open different pr's for a feature. Use the same pr to ask for a review which have been reviewed before.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-12-07 18:50 UTC, huzaifakhan0308 commented
> ## Invalid Code Review Request ❌
> Hi @huzaifakhan0308 ,
> 
> While you made a great effort in this project, unfortunately, I cannot proceed to review your code.
> 
> You have submitted a project, that doesn't have the correct github flow. I suggest you to change the base branch using this Github doc -> [Changing the base branch of a pull request](https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-base-branch-of-a-pull-request)
> 
> * Also, please don't open different pr's for a feature. Use the same pr to ask for a review which have been reviewed before.
> 
> Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏
> 
> Cheers and Happy coding!👏👏👏
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.
> 
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> 
> _Invalid Code Review Request **does not count** into the code reviews limit._

Now, what should i do with the 2nd branch (creating-form) . Should I delete it and  make changes in the 1st branch (main-changes).
These branches are already  with the base branch (personal-portfolio)
and if you told me something else, please clarify I didn't understand your point

2022-12-07 19:25 UTC, huzaifakhan0308 commented
Now, what should i do with the 2nd branch (creating-form) . Should I delete
it and make changes in the 1st branch (main-changes).
These branches are already with the base branch (personal-portfolio)
and if you told me something else, please clarify I didn't understand your
point

On Wed, 7 Dec 2022 at 23:22, Tuğsem Saranlı ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
> Invalid Code Review Request ❌
>
> Hi @huzaifakhan0308 <https://github.com/huzaifakhan0308> ,
>
> While you made a great effort in this project, unfortunately, I cannot
> proceed to review your code.
>
> You have submitted a project, that doesn't have the correct github flow. I
> suggest you to change the base branch using this Github doc -> Changing
> the base branch of a pull request
> <https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-base-branch-of-a-pull-request>
>
>    - Also, please don't open different pr's for a feature. Use the same
>    pr to ask for a review which have been reviewed before.
>
> Your Code Review Request will be marked as invalid in your Dashboard, so
> please submit a new one once you are ready 🙏
>
> Cheers and Happy coding!👏👏👏
>
> Feel free to leave any questions or comments in the PR thread if something
> is not 100% clear.
> Please, remember to tag me in your question so I can receive the
> notification.
>
> *Please, do not open a new Pull Request for re-reviews. You should use the
> same Pull Request submitted for the first review, either valid or invalid
> unless it is requested otherwise.*
> ------------------------------
>
> *Invalid Code Review Request does not count into the code reviews limit.*
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/huzaifakhan0308/personal-portfolio/pull/4#pullrequestreview-1208914486>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A3I36YCPF4MARXRGVGMNVVTWMDIW5ANCNFSM6AAAAAASXEL53Q>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-12-08 10:04 UTC, Qoosim requested changes
#  *Status: Required Changes* :recycle:

Hi @huzaifakhan0308, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
-  No linter errors. :heavy_check_mark: 
-  Good README file. :heavy_check_mark: 
-  Correct GitHub Flow. :heavy_check_mark: 

![](https://camo.githubusercontent.com/56bcd754643682fcc078b66eaa7278dead6c9c5013595c875b4ddcbe0f0ef0aa/68747470733a2f2f6d65646961302e67697068792e636f6d2f6d656469612f78554f786668365a4d373565664d3342716f2f67697068792d646f776e73697a65642d6d656469756d2e676966)


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-08 10:04 UTC, Qoosim commented on index.css
> +}
- [ ] I would like recommend you to consider adding more padding to your `Get in Touch` button in order to be inline with the design on the figma template.

### Your Design
![your-btn](https://user-images.githubusercontent.com/26597432/206417913-1726d70b-cff4-4352-91de-db405b102df9.png)

### Figma Design
![figma-btn](https://user-images.githubusercontent.com/26597432/206417945-4ca3dfa6-0ebc-4cf0-a1a6-7d7c17f9c4d0.png)

2022-12-08 10:04 UTC, Qoosim commented on index.css
> +}
- [ ] In order to get close replica of the guiding template, you need to produce almost the same design like we have on the figma design. Kindly compare your design with the figma design and work your design alongside figma design.

### Your Design
![your-form](https://user-images.githubusercontent.com/26597432/206416786-30a53169-8f66-44d4-9d48-19c26b36bc04.png)

### Figma Design
![figma-design](https://user-images.githubusercontent.com/26597432/206416822-9d320012-ab2b-43fa-ae58-cf7267e3fae7.png)

2022-12-08 11:16 UTC, Favourezeugwa approved these changes
## STATUS: APPROVED 🥇 🏆 🍹 

Hi @huzaifakhan0308, 

I am Favour 👩🏽 , your reviewer for this Pull Request. 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Yayyy! 💃🏽, Congratulations! 🎉 🎉🎉

![happy](https://user-images.githubusercontent.com/99246359/202491301-53f8c6a2-8ff4-4337-9b6b-9c75c8bdf345.gif)

## Highlights 💯 
- No Linter errors ✔️
- Good commit messages ✔️
- Professional Readme file ✔️
- Descriptive PR ✔️ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-08 16:36 UTC, merged